Task 3 Selenium WE
OleksandrBerezhnyi/Berezhman_test_aqa pull request #2
Opened 2021-01-14 11:40 UTC by OleksandrBerezhnyi

2021-01-15 18:22 UTC, DmitriyBondarenko commented on src/main/java/ua/yakaboo/Pages/LoginPage.java
> +//    @FindBy ()
Remove this comments please

2021-01-15 18:24 UTC, DmitriyBondarenko commented on src/test/java/ua/yakaboo/Tests/HomePageTest.java
> +        Assert.assertTrue(title.equals("Yakaboo — Інтернет-магазин книг, подарунків і дитячих товарів. Купити книги та подарунки по найкращим в Україні цінами."));
`Assert.assertEquals(title, "");`

2021-01-15 18:26 UTC, DmitriyBondarenko commented on src/main/java/ua/yakaboo/Pages/CartPage.java
> +package ua.yakaboo.Pages;
All packages should be from lower case

2021-01-15 18:26 UTC, DmitriyBondarenko commented on src/main/java/ua/yakaboo/Pages/HeaderPage.java
> +package ua.yakaboo.Pages;
All package name should be from lower case

2021-01-15 18:26 UTC, DmitriyBondarenko commented on src/main/java/ua/yakaboo/Pages/HomePage.java
> +package ua.yakaboo.Pages;
All package name should be from lower case

2021-01-15 18:27 UTC, DmitriyBondarenko commented on src/test/java/ua/yakaboo/Tests/BaseTests.java
> +package ua.yakaboo.Tests;
From lower case please

2021-01-15 18:29 UTC, DmitriyBondarenko requested changes
comments

2021-01-18 08:35 UTC, OleksandrBerezhnyi commented on src/main/java/ua/yakaboo/Pages/CartPage.java
> +package ua.yakaboo.Pages;
Updated

2021-01-18 08:36 UTC, OleksandrBerezhnyi commented on src/test/java/ua/yakaboo/Tests/BaseTests.java
> +package ua.yakaboo.Tests;
Updated

2021-01-18 09:03 UTC, OleksandrBerezhnyi commented on src/test/java/ua/yakaboo/Tests/HomePageTest.java
> +        Assert.assertTrue(title.equals("Yakaboo — Інтернет-магазин книг, подарунків і дитячих товарів. Купити книги та подарунки по найкращим в Україні цінами."));
Fixed

2021-01-18 09:04 UTC, OleksandrBerezhnyi commented on src/main/java/ua/yakaboo/Pages/LoginPage.java
> +//    @FindBy ()
Removed

2021-01-18 15:37 UTC, DmitriyBondarenko commented on src/test/java/ua/yakaboo/tests/BaseTests.java
> +    public WebDriver driver;
`protected DriverProvider driver;`

2021-01-18 15:38 UTC, DmitriyBondarenko commented on src/main/java/utils/driverUtils/DriverProvider.java
> +package utils.driverUtils;
just `driver`

2021-01-18 16:09 UTC, OleksandrBerezhnyi commented on src/main/java/utils/driverUtils/DriverProvider.java
> +package utils.driverUtils;
Renamed

2021-01-18 16:26 UTC, merged